audiolat: refactor main code
sdk28 build works:

```
$ ./gradlew buildAudiolat_sdk28ReleasePreBundle

> Task :app:externalNativeBuildAudiolat_sdk28Release
Build audiolat_sdk28_armeabi-v7a
ninja: Entering directory `audiolat/app/.cxx/cmake/audiolat_sdk28Release/armeabi-v7a'
ninja: no work to do.
Build audiolat_sdk28_arm64-v8a
ninja: Entering directory `audiolat/app/.cxx/cmake/audiolat_sdk28Release/arm64-v8a'
ninja: no work to do.

BUILD SUCCESSFUL in 874ms
28 actionable tasks: 2 executed, 26 up-to-date
```

But vanilla build is broken:

```
$ ./gradlew build
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:

  audiolat/app/src/main/java/com/facebook/audiolat/JavaAudio.java:66: Error: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException [MissingPermission]
          new AudioRecord.Builder()
          ^
...

BUILD FAILED in 4s
117 actionable tasks: 22 executed, 95 up-to-date
```

This happens before this task too, so we may as well build this one.